CREATE TABLE "DragBattles" (
    "ID" INTEGER NOT NULL UNIQUE,
    "Date" DATETIME NOT NULL,
    "Ch" INTEGER NOT NULL,
    "Opponents" TEXT NOT NULL,
    "Winner" INTEGER NOT NULL,
    "ResultID" INTEGER NOT NULL,
    "ET" DOUBLE,
    "ReactionTime" DOUBLE,
    "TrapSpeed" DOUBLE,
    "Time60Ft" DOUBLE,
    "Time330Ft" DOUBLE,
    "Time660Ft" DOUBLE,
    "Time1000Ft" DOUBLE,
    "CarCh" TEXT NOT NULL,
    "LocationID" INTEGER NOT NULL,
    "TrackTypeID" INTEGER NOT NULL,
    "DirectionID" INTEGER NOT NULL,
    "Payout" DOUBLE NOT NULL DEFAULT 0,
    PRIMARY KEY("ID" AUTOINCREMENT)
);

ALTER TABLE Players ADD COLUMN DragBattles INTEGER NOT NULL DEFAULT 0;
