//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Alex McBride")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("A light-weight InSim library for .NET 6 (min. LFS version: 0.6W)")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("6.0.3.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("6.0.3.1+bf2be0d465b300191ff9eae0b203825d7d79aff5")]
[assembly: System.Reflection.AssemblyProductAttribute("InSimDotNet")]
[assembly: System.Reflection.AssemblyTitleAttribute("InSimDotNet")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.0.3.1")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/alexmcbride/insimdotnet")]

// Generated by the MSBuild WriteCodeFragment class.

