//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSimDotNet {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("InSimDotNet.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InSimConnectedMessage {
            get {
                return ResourceManager.GetString("InSimConnectedMessage", resourceCulture);
            }
        }
        
        internal static string InSimConnectionLostMessage {
            get {
                return ResourceManager.GetString("InSimConnectionLostMessage", resourceCulture);
            }
        }
        
        internal static string InSimCouldNotConnectMessage {
            get {
                return ResourceManager.GetString("InSimCouldNotConnectMessage", resourceCulture);
            }
        }
        
        internal static string InSimInvalidVersionMessage {
            get {
                return ResourceManager.GetString("InSimInvalidVersionMessage", resourceCulture);
            }
        }
        
        internal static string InSimNotConnectedMessage {
            get {
                return ResourceManager.GetString("InSimNotConnectedMessage", resourceCulture);
            }
        }
        
        internal static string InSimRelayUdpErrorMessage {
            get {
                return ResourceManager.GetString("InSimRelayUdpErrorMessage", resourceCulture);
            }
        }
        
        internal static string IsAxmInfoErrorMessage {
            get {
                return ResourceManager.GetString("IsAxmInfoErrorMessage", resourceCulture);
            }
        }
        
        internal static string IsIPBInfoErrorMessage {
            get {
                return ResourceManager.GetString("IsIPBInfoErrorMessage", resourceCulture);
            }
        }
        
        internal static string IsMalInfoErrorMessage {
            get {
                return ResourceManager.GetString("IsMalInfoErrorMessage", resourceCulture);
            }
        }
        
        internal static string IsPLHInfoErrorMessage {
            get {
                return ResourceManager.GetString("IsPLHInfoErrorMessage", resourceCulture);
            }
        }
        
        internal static string IsReoPlidErrorMessage {
            get {
                return ResourceManager.GetString("IsReoPlidErrorMessage", resourceCulture);
            }
        }
        
        internal static string IsAicPlidErrorMessage {
            get {
                return ResourceManager.GetString("IsAicPlidErrorMessage", resourceCulture);
            }
        }
        
        internal static string PacketSizeErrorMessage {
            get {
                return ResourceManager.GetString("PacketSizeErrorMessage", resourceCulture);
            }
        }
        
        internal static string TcpSocketDebugErrorMessage {
            get {
                return ResourceManager.GetString("TcpSocketDebugErrorMessage", resourceCulture);
            }
        }
        
        internal static string UdpSocketDebugErrorMessage {
            get {
                return ResourceManager.GetString("UdpSocketDebugErrorMessage", resourceCulture);
            }
        }
    }
}
